### PR TITLE
[fix] put item removal outside of the loop

### LINKED ISSUE #82: Caught Errors in `enhanced 'for'` Loop
Hi👋
I got some errors at `WaterfallCloudGenerators.tickParticles(WaterfallCloudGenerators.java:67)`. 

`java.lang.ArrayIndexOutOfBoundsException`:
[crash-2022-04-27_17.51.03-client.txt](https://github.com/Ladysnake/Effective/files/8571544/crash-2022-04-27_17.51.03-client.txt)

`java.lang.NullPointerException`:
[crash-2022-04-27_21.40.56-client.txt](https://github.com/Ladysnake/Effective/files/8572065/crash-2022-04-27_21.40.56-client.txt)

I feel that the crash rate is particularly high when moving chunks around. So I tried these test codes:

```java
public class Main {
    public static final Object2IntMap<BlockPos> particlesToSpawn = new Object2IntOpenHashMap<>();

    public static void main(String[] args) throws InterruptedException {
        particlesToSpawn.put(new BlockPos(0, 0, 8), 3);
        particlesToSpawn.put(new BlockPos(0, 0, 1), 0);
        particlesToSpawn.put(new BlockPos(0, 0, 4), 0);
        particlesToSpawn.put(new BlockPos(0, 0, 0), 2);

        Thread updater1 = new Thread(Main::updateParticles);
        Thread updater2 = new Thread(Main::updateParticles);
        updater1.start();
        updater2.start();
        updater1.join();
        updater2.join();
    }

    public static void updateParticles() {
        for (BlockPos pos : particlesToSpawn.keySet()) {
            if (pos != null) {
                if (particlesToSpawn.put(pos, particlesToSpawn.getInt(pos) - 1) <= 0) {
                    particlesToSpawn.removeInt(pos);
                }
                System.out.printf("%s, particlesToSpawn.size() == %d%n", pos, particlesToSpawn.size());
            }
        }
    }
}
```

... and I got `java.lang.NullPointerException`.

Perhaps this crash seems to be caused by deletion in the `enhanced 'for'` loop.

https://github.com/Ladysnake/Effective/blob/9bd3c7d6f78cdf431082e6be43c8039dc9023658/src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java#L70

By enclosing this with `synchronized` and replacing `ObjectSet<Object2IntMap.Entry<K>>#removeIf(Predicate)`, I have not had any problems so far.

Thanks for awesome mod!

### LINKED ISSUE #86: Waterfall Cloud Generator Crash: Crashes Server
I'm not super sure what is going on other than the stacktrace almost immediately pointing here. I was playing on the Deathdusk Discord roleplay server and it crashed the server itself.

This is a server-side crash report that I obtained from the mod who was looking into this issue with me.
https://bytebin.lucko.me/Us7xVNKaww

### PR DESCRIPTION
**Pull request by lonefelidae16**
fixes #82, fixes #86

* avoid `ArrayIndexOutOfBoundsException`
* avoid `NullPointerException`

### CODE REVIEW

File: src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java [hunk 1]
```diff
@@ -64,13 +64,14 @@ public static void tick() {
     }
 
     private static void tickParticles(World world) {
-        for (BlockPos pos : particlesToSpawn.keySet()) {
-            if (pos != null) {
-                if (particlesToSpawn.put(pos, particlesToSpawn.getInt(pos) - 1) <= 0) {
-                    particlesToSpawn.removeInt(pos);
+        synchronized (particlesToSpawn) {
```
Comment (magneticflux-) [inline src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java:67]: I don't think this `synchronized` block does anything because the particles are not being ticked from multiple threads simultaneously.

File: src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java [hunk 2]
```diff
@@ -64,13 +64,14 @@ public static void tick() {
...
+            for (BlockPos pos : particlesToSpawn.keySet()) {
+                if (pos != null) {
+                    particlesToSpawn.put(pos, particlesToSpawn.getInt(pos) - 1);
```
Comment (magneticflux-) [inline src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java:70]: The `computeX` family of methods exists to encapsulate the `put(x, get(x))` pattern.

**Review by magneticflux- — CHANGES_REQUESTED** [review]

File: src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java [hunk 3]
```diff
@@ -64,13 +64,14 @@ public static void tick() {
...
+                    addWaterfallCloud(world, pos);
                 }
-                addWaterfallCloud(world, pos);
             }
+            particlesToSpawn.object2IntEntrySet().removeIf(blockPosEntry -> blockPosEntry.getIntValue() < 0);
         }
     }
```
Comment (magneticflux-) [inline src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java:76]: Here's my suggestion as a quick fix:

```suggestion
    private static void tickParticles(World world) {
        for (BlockPos pos : particlesToSpawn.keySet()) {
            if (pos != null) {
                particlesToSpawn.computeInt(pos, (blockPos, integer) -> integer - 1);
                addWaterfallCloud(world, pos);
            }
        }
        particlesToSpawn.values().removeIf(integer -> integer < 0);
    }
```

Comment (magneticflux-) [inline src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java:76]: `synchronized` doesn't do anything because particles aren't ticked on different threads. Additionally, `Map`s include methods to do the removals in a more streamlined manner:

```suggestion
    private static void tickParticles(World world) {
        for (BlockPos pos : particlesToSpawn.keySet()) {
            if (pos != null) {
                particlesToSpawn.computeInt(pos, (blockPos, integer) -> integer - 1);
                addWaterfallCloud(world, pos);
            }
        }
        particlesToSpawn.values().removeIf(integer -> integer < 0);
    }
```

**Review by magneticflux- — CHANGES_REQUESTED** [review]

File: src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java (hunk 3 above)
Comment (lonefelidae16) [reply src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java:76]: It's shorter! You've been very helpful.
And..., I found a bit of mistake.

Comment (lonefelidae16) [reply src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java]: This suggestion is included in 34fdfba .

**Review by magneticflux- — CHANGES_REQUESTED** [review]

File: src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java [hunk 4]
```diff
@@ -66,12 +66,11 @@ public static void tick() {
...
         for (BlockPos pos : particlesToSpawn.keySet()) {
             if (pos != null) {
-                if (particlesToSpawn.put(pos, particlesToSpawn.getInt(pos) - 1) <= 0) {
-                    particlesToSpawn.removeInt(pos);
-                }
+                particlesToSpawn.computeInt(pos, (blockPos, integer) -> integer - 1);
                 addWaterfallCloud(world, pos);
             }
         }
+        particlesToSpawn.values().removeIf(integer -> integer <= 0);
```
[the remark this answers is not in the document]
Comment (lonefelidae16) [reply src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java:73]: So, the value is already less than `0` when  `put` returns `0` ?

[the remark this answers is not in the document]
Comment (lonefelidae16) [reply src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java:73]: > So, the value is already less than `0` when `put` returns `0` ?

Oh my, it's true. The part I thought was my mistake was wrong.

[the remark this answers is not in the document]
Comment (lonefelidae16) [reply src/main/java/ladysnake/effective/client/world/WaterfallCloudGenerators.java]: Many thanks! I learned a lot.

Your suggestion was committed in 16d61a0 .

**Review by magneticflux- — APPROVED** [review]

**Comment by doctor4t** [comment]
Great contribution! Thank you very much :)
