### PR TITLE
Rewrite generators to be less laggy, fixed too many sounds playing ma…

### LINKED ISSUE #9: Game crashes sometimes when getting in range of a waterfall
I'm running on 1.18 with optifabric and a sildurs shaders. Sometimes when I load in a waterfall in my server it crashes the whole game. It seems to be an issue at `WaterfallCloudGenerators.tick(WaterfallCloudGenerators.java:30)` as seen in the crash log below. 

This mod is super awesome and have been looking for something like it for a long time and would love to see it be polished up nicely. 

> [17:03:16] [Render thread/FATAL]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1631) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at ladysnake.effective.client.world.WaterfallCloudGenerators.tick(WaterfallCloudGenerators.java:30) ~[effective-1.0.jar:?]
	at ladysnake.effective.client.Effective.lambda$onInitializeClient$2(Effective.java:121) ~[effective-1.0.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:111) ~[fabric-lifecycle-events-v1-1.4.10+c15ca33514-d830d5ce9751719.jar:?]
	at net.minecraft.class_638.handler$zki000$tickWorldAfterBlockEntities(class_638.java:3100) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:483) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:251) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1751) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1086) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
[17:03:17] [Render thread/INFO]: Clearing audio channels
[17:03:17] [Render thread/INFO]: Stopping microphone thread
[17:03:17] [Render thread/INFO]: Disconnecting voicechat
[17:03:17] [Render thread/INFO]: [STDOUT]: Minimap session finalized.
[17:03:17] [Render thread/INFO]: Removing the schematic world...
[17:03:18] [Thread-1/INFO]: Minecraft instance shutting down, starting the Illuminations uninstaller

**Edit:** Looking at the source code at that error, I think I see what's going on. A waterfallCloudGenerator is being modified while the lambda expression on line 30 is being executed. This could probably be fixed by using a standard for loop instead such as: 

        List<WaterfallCloudGenerator> generatorsInDistance = new List<WaterfallCloudGenerator>();
        for(int i=0; i<generator.size(); i++){
            if(generators[i].world == MinecraftClient.getInstance().player.world &&
             Math.sqrt(generators[i].blockPos.getSquaredDistance(MinecraftClient.getInstance().player.getBlockPos())) 
         <= MinecraftClient.getInstance().options.viewDistance * 8f){
             generatorsInDistance.add(generators[i]);
         }
        }

There may be a good reason for it, but this looks sort of inefficient at first glance. All the generators in the view distance are being collected into a list, then that list is looped over as well to add the cloud effects to. Would it not be faster to simply loop over all the WaterfallGenerators in the main list 'generators' in one loop and check if it is within render distance all in one go rather than having multiple loops and lists to take up extra resources with. Something like this:

      for (WaterfallCloudGenerator waterfallCloudGenerator : generatorsInDistance) {
            if(generators[i].world == MinecraftClient.getInstance().player.world &&
             Math.sqrt(generators[i].blockPos.getSquaredDistance(MinecraftClient.getInstance().player.getBlockPos())) 
         <= MinecraftClient.getInstance().options.viewDistance * 8f){
            World world = waterfallCloudGenerator.world;
            BlockPos blockPos = waterfallCloudGenerator.blockPos;
            if (!(world.getBlockState(blockPos).getBlock() == Blocks.WATER && world.getBlockState(blockPos).getFluidState().isStill() && world.getBlockState(blockPos.add(0, 1, 0)).getBlock() == Blocks.WATER && !world.getBlockState(blockPos.add(0, 1, 0)).getFluidState().isStill() && world.getBlockState(blockPos.add(0, 1, 0)).getFluidState().getHeight() >= 0.77f)) {
                generatorsToRemove.add(waterfallCloudGenerator);
            }

            if (world.random.nextInt(1) == 0 && world.getBlockState(blockPos).getBlock() == Blocks.WATER && world.getBlockState(blockPos).getFluidState().isStill() && world.getBlockState(blockPos.add(0, 1, 0)).getBlock() == Blocks.WATER && !world.getBlockState(blockPos.add(0, 1, 0)).getFluidState().isStill() && world.getBlockState(blockPos.add(0, 1, 0)).getFluidState().getHeight() >= 0.77f) {
                double offsetX = world.random.nextGaussian() / 5f;
                double offsetZ = world.random.nextGaussian() / 5f;

                world.playSound(blockPos.getX(), blockPos.getY(), blockPos.getZ(), Effective.AMBIENCE_WATERFALL, SoundCategory.AMBIENT, 2.5f, 1.2f + world.random.nextFloat() / 10f, true);
                world.addParticle(Effective.WATERFALL_CLOUD, blockPos.getX() + .5 + offsetX, blockPos.getY() + 1 + world.random.nextFloat(), blockPos.getZ() + .5 + offsetZ, world.random.nextFloat() / 5f * Math.signum(offsetX), world.random.nextFloat() / 5f, world.random.nextFloat() / 5f * Math.signum(offsetZ));
            }
         }
        }

### PR DESCRIPTION
**Pull request by Sollace**
…king it louder than it was meant to be, and fixed waterfalls being generated on submerged/short falls.

 1. Check distance to the player before trying to add a waterfall generator
 2. Changed the generators list to a Set and override hashCode() in the generator to prevent it from adding duplicate generators
 3. Rewrote tick() to only have to iterate the generators once per tick
 4. Remove generators that are out of range or invalid before they try to add sounds and particles
 5. Play a sound once every 15 ticks (rather than every tick) (I found the mod was capping the game's limit for concurrent sounds playing, which is likely the cause for some people's lag)
 6. To balance the effect of duplicates no longer being created, bumped up the number of particles each one spawns per tick
 7. Adjusted the volume on the waterfall sounds
 8. Removed redundant state checks in the tick method
 9. Fixed (no issue number) underwater waterfalls and waterfalls on zero-block drops. I just added `&& above.getFluidState().get(FlowableFluid.FALLING)` to the usual checks.

Edit:
10. Removed the BlockRenderManagerMixin and moves its contents along with the displayTick callback into WaterFluidMixin. This should resolve conflicts with Canvas/Sodium/Iris or whatever other mod operates on world rendering. As such, this PR now supercedes #17 

Also because both interactions with generators are happening in the client world tick, this should also fix #9

All relevant issues: #27, #26, #17, #11, #10 (maybe), #9, #3, #2

### CODE REVIEW

**Comment by DimetryBadcoder** [comment]
Do you have fixed mod build? 
It would be nice to have one :)

**Comment by Sollace** [comment]
> Do you have fixed mod build? It would be nice to have one :)

Since the developer appears to be MIA, I can certainly get you a build, though I would also look at fixing the problem with sodium/iris/canvas/indium/etc before I do.

**Comment by Sollace** [comment]
Aight. Updated description with new details.

**Comment by Sollace** [comment]
Jar can be found on the releases page for my fork. https://github.com/Sollace/Effective/releases/tag/1.1.0

**Comment by DimetryBadcoder** [comment]
> Jar can be found on the releases page for my fork. https://github.com/Sollace/Effective/releases/tag/1.1.0

Many thanks!

**Comment by Pyrofab** [comment]
> waterfalls on zero-block drops
I believed rat didn't want to fix that because some waterfall look like this (W = water, S = solid) 
W
W
WW
SWWWWW (sea)
If I understand correctly, such a waterfall would not be detected with your change.

File: src/main/java/ladysnake/effective/mixin/WaterFluidMixin.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
+
+import ladysnake.effective.client.world.WaterfallCloudGenerators;
+
+import java.util.Random;
+
+@Mixin(WaterFluid.class)
+abstract class WaterFluidMixin {
+    @Inject(method = "randomDisplayTick", at = @At("RETURN"))
+    private void illuminations$randomDisplayTick(World world, BlockPos pos, FluidState state, Random random, CallbackInfo ci) {
```
Comment (Pyrofab) [inline src/main/java/ladysnake/effective/mixin/WaterFluidMixin.java:21]: - Is this actually more performant ? As far as I know, the previous injection only ran upon chunk rebuild, not every frame.
- Is this as reactive as the previous injection ? If I understand correctly, a waterfall could stay undetected for quite a while if it didn't get a random update.

Comment (Sollace) [reply src/main/java/ladysnake/effective/mixin/WaterFluidMixin.java:21]: > Is this as reactive as the previous injection ?
I tested this and it does update reasonably quickly, yeah.

> Is this actually more performant ?
I didn't notice any measurable difference in performance. The advantage of doing it this way is that it will no longer conflict with Canvas and Sodium and you will no longer need that cursed workaround in #17

**Comment by Sollace** [comment]
> > waterfalls on zero-block drops
> 
> I believed rat didn't want to fix that because some waterfall look like this (W = water, S = solid) W W WW SWWWWW (sea) If I understand correctly, such a waterfall would not be detected with your change.

The situation I'm referring to is ones like this:

WW
SW

The situation you described will still work.

**Review by Pyrofab — APPROVED** [review]
LGTM, I'll let rat check before merging

**Comment by doctor4t** [comment]
One problem with this PR is that using random display tick isn't that good of an idea. Random display ticks only occur in a 32 block radius around the player, meaning you cannot see the cascade particles until you get close enough. I'll have to revert that part of the PR.

**Comment by MissLav** [comment]
> Jar can be found on the releases page for my fork. https://github.com/Sollace/Effective/releases/tag/1.1.0

The underwater waterfalls still happen for some reason with your build

**Comment by MissLav** [comment]
> > Jar can be found on the releases page for my fork. https://github.com/Sollace/Effective/releases/tag/1.1.0
> 
> The underwater waterfalls still happen for some reason with your build

heres a video of it happening https://cdn.discordapp.com/attachments/492169001858760704/925173749626585098/2021-12-27_17-44-55.mp4
